#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

# Function displaying usage message
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
}

# Check if less than 3 parameters passed
if [ "$#" -lt 4 ]; then
	usage
fi

# assign parameteres
PATH_TO_FILE="#1"
IP="#2"
USERNAME="#3"
PATH_TO_SSH_KEY="#4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
