#!/usr/bin/env bash
# Nginx configuration of web-02 web server with a custom http header

# Update package lists
sudo apt-get -y update && sudo apt-get -y upgrade

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a new configuration file for redirection
redirection_conf="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "24i $redirection_conf" /etc/nginx/sites-available/default

# Create a new configuration file for 404 not found error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
error_string="\\\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

# Add custom HTTP header to Nginx response
custom_header="\\\tadd_header X-Served-By \\\$HOSTNAME;"
sudo sed -i "25i $custom_header" /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo service nginx reload

