#!/usr/bin/env bash
# Configure HAProxy load balancer server

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat
apt-get -y update
apt-get -y install haproxy
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 490902-web-01 107.23.58.213
        server 490902-web-02 54.198.48.244" >> /etc/haproxy/haproxy.cfg

service haproxy restart
