#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line using while loop and if statement.
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "hi"
	else
		echo "Best School"
	fi
	((i++))
done
