#!/usr/bin/env bash
# A Bash script that gives you information about the school file.

file="school"
# Check if the file exists
if [ -e "$file" ]; then
	echo "school file exists"

	# Check if the file is empty
	if [ -s "$file" ]; then
		echo "school file is not empty"

		# Check if the file is a regular file
		if [ -f "$file" ]; then
			echo "school is a regular file"
		else
			# The file is not a regular file
			:
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi	
